# Splat config for Your Game
name: "Burnout 3: Takedown (USA)"
sha1: 332be40d6081b8b5055a6ea01194ad6ff662a863

options:
  basename: "SLUS_210.50"      # Change to your ELF's filename
  target_path: "disc/SLUS_210.50" # Change to your ELF's filename
  elf_path: "SLUS_210.50"         # Change to your ELF's filename
  base_path: ../
  platform: ps2
  compiler: EEGCC

  # --- Standard options from the original project ---
  asm_path: asm
  src_path: src
  build_path: obj

  # Assembly options
  generate_asm_macros_files: False
  named_regs_for_c_funcs: False
  find_file_boundaries: False
  disasm_unknown: True

  # Rodata options
  rodata_string_guesser_level: 0 # improve string detection
  suggestion_rodata_section_start: True
  pair_rodata_to_text: False
  migrate_rodata_to_functions: True

  # Auto-generate undefined functions and symbols
  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/undefined_syms_auto.txt

  # Manually defined symvols
  symbol_addrs_path: config/symbol_addrs_b3.txt

  # Splat extensions
  extensions_path: tools/splat_ext

  # (Include other standard options like create_undefined_funcs_auto, etc.)
  section_order: [".text", ".data", ".rodata", ".bss"] # A typical order
  auto_link_sections: [".data", ".rodata", ".bss"]
  subalign: 8

segments:
  - [0, databin, elf_header_and_padding]

  - name: main
    type: code
    start: 0x100
    vram: 0x100000
    bss_size: 0x1A0C380
    subsegments:
      - [0x100, asm, text1, {group: main}]
      - [0x1BF8B0, cpp, b3/CGtPolygonSoup]
      - [0x1BF8F0, asm, text2, {group: main}]
      - [0x2BE9D0, cpp, b3/CGtCollisionKDTree]
      - [0x2BFFE0, asm, text3, {group: main}]
      - [0x369E00, data]
  
  - [0x3E2780, databin, trailing_data]